name: Test Container
on:
  workflow_dispatch:
jobs:
  build-test:
    runs-on: ubuntu-latest
    steps:
      - name: Runner execution
        run: cat /etc/os-release

      - name: Container execution
        uses: docker://alpine:latest
        with:
          entrypoint: cat
          args: /etc/os-release
